name: skyblock_ical_generator
description: Generates an ical calendar for Skyblock Events
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ical_serializer: ^0.0.3